name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: lukka/run-vcpkg@v11
        with:
          vcpkgJsonGlob: 'vcpkg.json'

      - name: Configure CMake
        run: >
          cmake -B build -S .
          -DCMAKE_TOOLCHAIN_FILE=${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake
      -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build

      - name: Run Tests
        run: ctest --test-dir build --output-on-failure
